services:

  open-webui:

    image: ghcr.io/open-webui/open-webui:main

    container_name: open-webui

    restart: unless-stopped

    ports:
      - "3000:8080"

    volumes:
      - ./Services/open-webui:/app/backend/data

    environment:
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}

    extra_hosts:
      - host.docker.internal:host-gateway

  chromadb:

    image: chromadb/chroma

    container_name: chromadb

    restart: unless-stopped

    ports:
      - "8000:8000"

    volumes:
      - ./Services/chromadb:/chroma/chroma