"""Registry protocol."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class Registry(Protocol):
    """Central registry for dynamic component discovery."""

    def register(self, key: str, instance: Any) -> None: ...
    def resolve(self, key: str) -> Any: ...
    def has(self, key: str) -> bool: ...
    def list_all(self) -> list[str]: ...
    def unregister(self, key: str) -> None: ...
