"""ORBIT Git Engine."""

from orbit_git.engine import GitEngine
from orbit_git.events import (
    BlameCompleted,
    BranchCheckedOut,
    BranchCreated,
    BranchDeleted,
    BranchRenamed,
    CherryPickCompleted,
    CloneCompleted,
    CommitCreated,
    DiffGenerated,
    FetchCompleted,
    GitEvent,
    HistoryLoaded,
    MergeCompleted,
    PullCompleted,
    PushCompleted,
    RebaseCompleted,
    RemoteAdded,
    RemoteRemoved,
    RemoteRenamed,
)
from orbit_git.exceptions import (
    GitCommandError,
    GitError,
    RepositoryCorruptError,
    RepositoryNotFoundError,
)
from orbit_git.integration import GitKnowledgeService
from orbit_git.managers import BranchManager, CommitManager, DiffManager, HistoryManager, RemoteManager, RepositoryManager
from orbit_git.models import (
    BlameLine,
    Branch,
    Commit,
    Diff,
    DiffFile,
    DiffStats,
    FetchResult,
    GitResult,
    GitVersion,
    MergeResult,
    PullResult,
    PushResult,
    RebaseResult,
    Remote,
    Repository,
    RepositoryState,
    Status,
    StatusEntry,
)

__all__ = [
    "GitEngine",
    "GitKnowledgeService",
    "BranchManager",
    "CommitManager",
    "DiffManager",
    "HistoryManager",
    "RemoteManager",
    "RepositoryManager",
    "GitError",
    "RepositoryNotFoundError",
    "RepositoryCorruptError",
    "GitCommandError",
    "Repository",
    "RepositoryState",
    "GitVersion",
    "GitResult",
    "Status",
    "StatusEntry",
    "Branch",
    "Commit",
    "FetchResult",
    "MergeResult",
    "PullResult",
    "PushResult",
    "RebaseResult",
    "Remote",
    "Diff",
    "DiffFile",
    "DiffStats",
    "BlameLine",
    "GitEvent",
    "BranchCreated",
    "BranchDeleted",
    "BranchRenamed",
    "BranchCheckedOut",
    "MergeCompleted",
    "RebaseCompleted",
    "CommitCreated",
    "CherryPickCompleted",
    "RemoteAdded",
    "RemoteRemoved",
    "RemoteRenamed",
    "FetchCompleted",
    "PullCompleted",
    "PushCompleted",
    "CloneCompleted",
    "DiffGenerated",
    "HistoryLoaded",
    "BlameCompleted",
]
